#!/bin/bash
# chkconfig: 2345 20 80
# description: CloudWatch Agent service script

[ -f /etc/default/cloudwatch-agent ] && . /etc/default/cloudwatch-agent

if [ -z "$AWS_ACCESS_KEY_ID" ] ; then
    echo "AWS_ACCESS_KEY_ID is not set, please set it /etc/default/cloudwatch-agent" >&2
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ] && [ -z "$AWS_SECRET_KEY" ] ; then
    echo "AWS_SECRET_KEY or AWS_SECRET_ACCESS_KEY is missing, please set it /etc/default/cloudwatch-agent"
fi

start() {
    nohup /usr/sbin/cloudwatch-agent > /dev/null 2>&1 &
    echo $! > /var/run/cloudwatch-agent.pid
}

stop() {
    kill -2 $(cat /var/run/cloudwatch-agent.pid)
    rm -f /var/run/cloudwatch-agent.pid
}

status() {
    if [ -e /var/run/cloudwatch-agent.pid ] ; then
        echo "CloudWatch Agent seems up and running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0

