#!/bin/bash
# chkconfig: 2345 20 80
# description: CloudWatch Agent service script

[ -f /etc/default/cloudwatch-agent ] && . /etc/default/cloudwatch-agent

if [ -z "$AWS_ACCESS_KEY_ID" ] ; then
    echo "AWS_ACCESS_KEY_ID is not set, please set it /etc/default/cloudwatch-agent" >&2
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ] && [ -z "$AWS_SECRET_KEY" ] ; then
    echo "AWS_SECRET_KEY or AWS_SECRET_ACCESS_KEY is missing, please set it /etc/default/cloudwatch-agent"
fi

start() {
    nohup /usr/sbin/cloudwatch-agent -conf /etc/cloudwatch-agent/cloudwatch-agent.conf > /dev/null 2>&1 &
}

stop() {
    killall -2 cloudwatch-agent
}

check_process(){
    if [ "$1" = "" ];
    then
            return 0
    fi

    PROCESS_NUM=$(ps -ef | grep "$1" | grep -v "grep" | wc -l)

    if [ $PROCESS_NUM -eq 1 ]; then
        return 1
    else
        return 0
    fi
}

status() {
    check_process "cloudwatch-agent"
    CHECK_RET=$?

    if [ $CHECK_RET -eq 0 ]; then
        echo " * cloudwatch-agent is stopped"
    else
        echo " * cloudwatch-agent is running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0

